TWEAK_NAME = NoForcePortraitLock
$(TWEAK_NAME)_FILES = Tweak.xm 
$(TWEAK_NAME)_CFLAGS = -fobjc-arc -Wno-deprecated-declarations
$(TWEAK_NAME)_CCFLAGS = -Wc++11-extensions -std=c++11
# $(TWEAK_NAME)_LIBRARIES =
$(TWEAK_NAME)_FRAMEWORKS += UIKit Foundation
# $(TWEAK_NAME)_PRIVATE_FRAMEWORKS += MediaRemote FrontBoard BulletinBoard
# $(TWEAK_NAME)_EXTRA_FRAMEWORKS = Cephei

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk